from saas.core.exceptions import SaaSRuntimeException


class AppRuntimeError(SaaSRuntimeException):
    pass
